esphome:
  name: ${node_name}
  on_boot:
    - priority: -100
      then:
        - script.execute: on_boot
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
<<: !include aq-mood-base.yaml