esphome:
  name: ${node_name}
  on_boot:
    - priority: -100
      then:
        - script.execute: on_boot
esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
<<: !include aq-mood-base.yaml